#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker"
main = "src/worker.jsx"
compatibility_date = "2026-05-15"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "sublink", id = "2c57a7b73e6847388bf66b744906e391" }
]

[assets]
directory = "./public"
